### ISSUE TITLE
FR: env flex & new Plugins - Todo list

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#409]
- [ ] flexible/async-rest - shouldn’t be using Docker
- [ ] flexible/endpoints - does appengine:deploy work?
- [ ] flexible/* - See if we really want to use EnvVar’s to pass values,
perhaps we should modify to use web.xml context vars.
- [ ] flexible/memcache — NEED WORK

**Comment by lesv** [comment]
Obsolete
